version: "3.8"

services:
  app:
    container_name: photo-sharing-app
    image: photo-sharing-app
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
